CREATE TABLE STAFF (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(12) ,
    password VARCHAR(255) NOT NULL,
    lastname VARCHAR(255),
    branch_name VARCHAR(255),
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    blocked_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);